src/java/Controladores/ContenidoController.java
package Controladores;

import Modelos.Contenido;
import Controladores.util.JsfUtil;
import Controladores.util.JsfUtil.PersistAction;
import Conexiones.ContenidoFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@ManagedBean(name = "contenidoController")
@SessionScoped
public class ContenidoController implements Serializable {

    @EJB
    private Conexiones.ContenidoFacade ejbFacade;
    private List<Contenido> items = null;
    private Contenido selected;

    public ContenidoController() {
    }

    public Contenido getSelected() {
        return selected;
    }

    public void setSelected(Contenido selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private ContenidoFacade getFacade() {
        return ejbFacade;
    }

    public Contenido prepareCreate() {
        selected = new Contenido();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("ContenidoCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("ContenidoUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("ContenidoDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Contenido> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public List<Contenido> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Contenido> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Contenido.class)
    public static class ContenidoControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ContenidoController controller = (ContenidoController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "contenidoController");
            return controller.getFacade().find(getKey(value));
        }

        java.lang.Long getKey(String value) {
            java.lang.Long key;
            key = Long.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Long value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Contenido) {
                Contenido o = (Contenido) object;
                return getStringKey(o.getId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Contenido.class.getName()});
                return null;
            }
        }

    }

}

web/Vistas/contenido/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ContenidoCreateDlg" widgetVar="ContenidoCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateContenidoTitle}">
            <h:form id="ContenidoCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{contenidoController.selected != null}">                       
                        <p:outputLabel value="#{bundle.CreateContenidoLabel_clave}" for="clave" />
                        <p:inputText id="clave" value="#{contenidoController.selected.clave}" title="#{bundle.CreateContenidoTitle_clave}" required="true" requiredMessage="#{bundle.CreateContenidoRequiredMessage_clave}"/>
                        <p:outputLabel value="#{bundle.CreateContenidoLabel_valor}" for="valor" />
                        <p:inputText id="valor" value="#{contenidoController.selected.valor}" title="#{bundle.CreateContenidoTitle_valor}" required="true" requiredMessage="#{bundle.CreateContenidoRequiredMessage_valor}"/>
                        <p:outputLabel value="#{bundle.CreateContenidoLabel_idP}" for="idP" />
                        <p:selectOneMenu id="idP" value="#{contenidoController.selected.idP}" required="true" requiredMessage="#{bundle.EditContenidoRequiredMessage_idP}">
                            <f:selectItems value="#{paqueteController.itemsAvailableSelectOne}"
                                           var="idPItem"
                                           itemValue="#{idPItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{contenidoController.create}" value="#{bundle.Save}" update="display,:ContenidoListForm:datalist,:growl" oncomplete="handleSubmit(args,'ContenidoCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="ContenidoCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/Vistas/contenido/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ContenidoEditDlg" widgetVar="ContenidoEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditContenidoTitle}">
            <h:form id="ContenidoEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{contenidoController.selected != null}">                        
                        <p:outputLabel value="#{bundle.EditContenidoLabel_clave}" for="clave" />
                        <p:inputText id="clave" value="#{contenidoController.selected.clave}" title="#{bundle.EditContenidoTitle_clave}" required="true" requiredMessage="#{bundle.EditContenidoRequiredMessage_clave}"/>
                        <p:outputLabel value="#{bundle.EditContenidoLabel_valor}" for="valor" />
                        <p:inputText id="valor" value="#{contenidoController.selected.valor}" title="#{bundle.EditContenidoTitle_valor}" required="true" requiredMessage="#{bundle.EditContenidoRequiredMessage_valor}"/>
                        <p:outputLabel value="#{bundle.EditContenidoLabel_idP}" for="idP" />
                        <p:selectOneMenu id="idP" value="#{contenidoController.selected.idP}" required="true" requiredMessage="#{bundle.EditContenidoRequiredMessage_idP}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{paqueteController.itemsAvailableSelectOne}"
                                           var="idPItem"
                                           itemValue="#{idPItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{contenidoController.update}" value="#{bundle.Save}" update="display,:ContenidoListForm:datalist,:growl" oncomplete="handleSubmit(args, 'ContenidoEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="ContenidoEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/Vistas/contenido/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListContenidoTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="ContenidoListForm">
                <p:panel header="#{bundle.ListContenidoTitle}">
                    <p:dataTable id="datalist" value="#{contenidoController.items}" var="item"
                                 selectionMode="single" selection="#{contenidoController.selected}"
                                 paginator="true"
                                 rowKey="#{item.id}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListContenidoTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListContenidoTitle_clave}"/>
                            </f:facet>
                            <h:outputText value="#{item.clave}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListContenidoTitle_valor}"/>
                            </f:facet>
                            <h:outputText value="#{item.valor}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListContenidoTitle_idP}"/>
                            </f:facet>
                            <h:outputText value="#{item.idP}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{contenidoController.prepareCreate}" update=":ContenidoCreateForm" oncomplete="PF('ContenidoCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":ContenidoViewForm" oncomplete="PF('ContenidoViewDialog').show()" disabled="#{empty contenidoController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":ContenidoEditForm" oncomplete="PF('ContenidoEditDialog').show()" disabled="#{empty contenidoController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{contenidoController.destroy}" update=":growl,datalist" disabled="#{empty contenidoController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/Vistas/contenido/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ContenidoViewDlg" widgetVar="ContenidoViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewContenidoTitle}">
            <h:form id="ContenidoViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{contenidoController.selected != null}">
                        <h:outputText value="#{bundle.ViewContenidoLabel_id}"/>
                        <h:outputText value="#{contenidoController.selected.id}" title="#{bundle.ViewContenidoTitle_id}"/>
                        <h:outputText value="#{bundle.ViewContenidoLabel_clave}"/>
                        <h:outputText value="#{contenidoController.selected.clave}" title="#{bundle.ViewContenidoTitle_clave}"/>
                        <h:outputText value="#{bundle.ViewContenidoLabel_valor}"/>
                        <h:outputText value="#{contenidoController.selected.valor}" title="#{bundle.ViewContenidoTitle_valor}"/>
                        <h:outputText value="#{bundle.ViewContenidoLabel_idP}"/>
                        <h:outputText value="#{contenidoController.selected.idP}" title="#{bundle.ViewContenidoTitle_idP}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="ContenidoViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>